version: '2'

services:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
        - node.name=kifarunix-demo-es
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - http.host=0.0.0.0
        - network.host=0.0.0.0
        - network.bind_host= 0.0.0.0

    ports:
      - 9200:9200
      - 9300:9300